### ISSUE TITLE
macOS 使用 homebrew 安装后运行服务报错

### ISSUE THREAD

**Issue by XYZliang** [Mrered/Gobin#1]
因为 nezha 官方没有 issues，您的 github 和博客也没有任何联系方式，只能在您别的仓库提 issues 了。

环境变量上面的正常配置，但是还是运行出错：
```
brew services start nezha-agent
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist` exited with 5.
[15:20:03] [cost 1.375s] brew services start nezha-agent
```

试过 sudo 运行、start brewforge/chinese/nezha-agent、launchctl load /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist、/bin/launchctl bootstrap gui/501 /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist均是一样的报错

运行`brew services info nezha-agent`输出：
```
brew services info nezha-agent
nezha-agent (homebrew.mxcl.nezha-agent)
Running: ✘
Loaded: ✔
Schedulable: ✘
[15:57:21] [cost 1.645s] brew services info nezha-agent
```

使用 macbook pro m2pro，系统为最新beta 版本

**Comment by Mrered** [comment]
在此处继续跟进： https://github.com/Brewforge/homebrew-chinese/issues/215
